[book]
title = "mdBook 中文文档"
description = "mdbook :) markdown生成记. 就像 Gitbook, 但专为 Rust 设计"
authors = ["Mathieu David", "Michael-F-Bryan", "译:yobrave"]
language = "zh-CN"

[rust]
edition = "2018"

[build]
build-dir = "docs"
create-missing = true
use-default-preprocessors = false

[preprocessor.links]

[output.html]
mathjax-support = true
site-url = "/mdBook-zh/"
curly-quotes = true
git-repository-url = "https://github.com/chinanf-boy/mdBook-zh"
edit-url-template = "https://github.com/chinanf-boy/mdBook-zh/edit/master/{path}"

[output.html.playpen]
editable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
