[book]
title = "mdBook 中文文档"
description = "mdbook :) markdown生成记. 就像Gitbook, 但专为Rust设计"
authors = ["Mathieu David", "Michael-F-Bryan", "译:yobrave"]
language = "zh-CN"

[build]
build-dir = "docs"
create-missing = true
preprocess = ["links", "index"]

[output.html]
mathjax-support = true
theme = "src/theme"
curly-quotes = true
google-analytics = "UA-128555056-1"
additional-css = ["src/theme/custom.css"]
git_repository_url = "https://github.com/chinanf-boy/mdbook-zh"
git_repository_icon = "fa-github"

[output.html.playpen]
editable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
